n
Radoslava486/HerokuApp_Rada_Mishurova pull request #1
Opened 2022-07-04 22:34 UTC by Radoslava486

2022-07-04 22:39 UTC, Radoslava486 commented
Тесты не прошли в typos, notification messages, addRemove, sortableTables

2022-07-05 07:14 UTC, voropa requested changes

2022-07-05 07:14 UTC, voropa commented on src/main/java/Puma.html
> +<!DOCTYPE html>
Обратите внимание на errors and warnings, которые  показывает IDEA в этом html файле и исправьте их по возможности (хотя бы errors)
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/14195681/177269467-06ed0809-355e-4971-9e8a-dc9371ce1968.png">

2022-07-05 07:14 UTC, voropa commented on src/test/java/AddRemoveElementsTest.java
> +            Assert.assertEquals(deleteButtons.size(), 1, "One button remains");
Верно, потому что в 24 строке вы кликнули на кнопку, элемент удалился, а в переменной deleteButtons у вас по-прежнему массив из 2х кнопок. Вам нужно заново перенеинициализировать этот массив через driver.findElements

2022-07-05 07:14 UTC, voropa commented on src/test/java/DropdownTest.java
> +        Assert.assertEquals(driver.findElement(By.xpath("//select[@id='dropdown']/option[@value='2']")).isSelected(), true, "Option 2 is selected");
Когда мы работает с классом select, то опции в нем не нужно искать через findElements, так как все необходимые методы есть в самом классе селект. Для проверки того, что опция выбрана, нужно воспользоваться следующим методом: select.getFirstSelectedOIption().getText()

2022-07-05 07:14 UTC, voropa commented on src/test/java/NotificationMessages.java
> +        driver.findElement(By.xpath("<a href=\\\"/notification_message\\\">Click here</a>")).click();
Что-то вы намудрили с локатором тут, попробуйте вот такой: By.linkText("/notification_message")

2022-07-05 07:14 UTC, voropa commented on src/test/java/Typos.java
> +        String actualResult = driver.findElement(By.tagName("p")).getText();
С таким локатором, вы получаете текст из верхнего параграфа, а вам нужен текст из нижнего (второго)
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/14195681/177270884-f1ea2ca5-5a19-4b67-9207-4befd1868b2d.png">

Так что воспользуйтесь fiondElement**s** и возьмите второй p из массива

2022-07-05 22:12 UTC, Radoslava486 commented on src/test/java/NotificationMessages.java
> +        driver.findElement(By.xpath("<a href=\\\"/notification_message\\\">Click here</a>")).click();
тоже не срабатывает

2022-07-11 21:39 UTC, voropa approved these changes

2022-07-14 13:19 UTC, merged